### ISSUE TITLE
Add sleep for mac

### ISSUE THREAD

**Issue by reinhillmann** [arjun024/turn-off-screen#1]
# !/usr/bin/python

import subprocess
subprocess.call('echo "tell application \"Finder\" to sleep" | osascript ', shell=True)

**Comment by aslily1234** [comment]
subprocess.call('echo \'tell application "Finder" to sleep\' | osascript', shell=True)  is not ok for my mac.

but 
os.system("pmset displaysleepnow")  is ok for my mac
